Extend import suggestions for more than one option
haskell/ghcide pull request #913
Opened 2020-11-17 14:14 UTC by gdevanla

Fixes #792.

2020-11-17 21:37 UTC, pepeiborra requested changes
Thanks for the fix! I have been annoyed by this bug quite a few times.
Some minor changes needed before merging it

2020-11-17 21:37 UTC, pepeiborra commented on src/Development/IDE/Plugin/CodeAction.hs
> +      Nothing -> Nothing
Avoid duplicated code: rewrite in terms of `matchRegex` (line 1117)

2020-11-17 21:37 UTC, pepeiborra commented on src/Development/IDE/Plugin/CodeAction.hs
> +      [x, xs] -> Just (x, xs)
use `matchRegexUnifySpaces`

2020-11-17 21:37 UTC, pepeiborra commented on test/exe/Main.hs
> +      "Add fromList to the import list of Data.HashMap.Strict"
don't we need an additional check for `Data.Map`?

2020-11-17 21:37 UTC, pepeiborra commented on test/exe/Main.hs
> +    , testSession "parse malformed import list" $ template
You don't need to spin up a ghcide session for these tests, right?
```suggestion
      testCase "parse invalid multiple imports" $ template "foo bar foo" Nothing
    , testCase "parse malformed import list" $ template
```

2020-11-18 16:01 UTC, gdevanla commented
I have a question about `testSession`. Is the `testSession` persisted across runs, I can different results, when I run the same tests multiple time: Here is an example:

```
$ stack test --test-arguments '--pattern "extend import list with multiple choices"' --fast 
ghcide> test (suite: ghcide-tests, args: --pattern "extend import list with multiple choices")

ghcide> ghcide
ghcide>   code actions
ghcide>     extend import actions
ghcide>       extend import list with multiple choices: FAIL
ghcide>         Exception: Received an unexpected message from the server:
ghcide>         Was parsing: Pattern match failure in do expression at test/exe/Main.hs:1125:7-65
ghcide>         Last message received:
ghcide>         {
ghcide>             "tag": "RspCodeAction",
ghcide>             "contents": {
ghcide>                 "result": [],
ghcide>                 "jsonrpc": "2.0",
ghcide>                 "id": 1
ghcide>             }
ghcide>         }
ghcide> 
ghcide> 1 out of 1 tests failed (2.34s)
ghcide> Test suite ghcide-tests failed
Test suite failure for package ghcide-0.5.0
    ghcide-tests:  exited with: ExitFailure 1
Logs printed to console


#  ~/fsf/hls/ghcide on git:fe273b3 x C:1
$ stack test --test-arguments '--pattern "extend import list with multiple choices"' --fast 
ghcide> test (suite: ghcide-tests, args: --pattern "extend import list with multiple choices")

ghcide> ghcide
ghcide>   code actions
ghcide>     extend import actions
ghcide>       extend import list with multiple choices: OK (2.63s)
ghcide> 
ghcide> All 1 tests passed (2.63s)
ghcide> Test suite ghcide-tests passed
```

2020-11-18 16:30 UTC, gdevanla commented
Question:  I get different results from calling `testSession`. May be is it because of some timeout issues?

```
#  ~/fsf/hls/ghcide on git:extend-import-suggestions-for-more-than-one-option x C:1
$ time stack test --test-arguments '--pattern "extend import list with"' --fast
ghcide> test (suite: ghcide-tests, args: --pattern "extend import list with")

ghcide> ghcide
ghcide>   code actions
ghcide>     extend import actions
ghcide>       extend import list with multiple choices:
ghcide> No of code actions = 0
ghcide> FAIL
ghcide>         Exception: test/exe/Main.hs:(1126,11)-(1127,82): Non-exhaustive patterns in CACodeAction action@CodeAction {_title = actionTitle} : _
ghcide>
ghcide> 1 out of 1 tests failed (2.46s)
ghcide> Test suite ghcide-tests failed
Test suite failure for package ghcide-0.5.0
    ghcide-tests:  exited with: ExitFailure 1
Logs printed to console

stack test --test-arguments '--pattern "extend import list with"' --fast  2.33s user 0.60s system 102% cpu 2.863 total

#  ~/fsf/hls/ghcide on git:extend-import-suggestions-for-more-than-one-option x C:1
$ time stack test --test-arguments '--pattern "extend import list with"' --fast
ghcide> test (suite: ghcide-tests, args: --pattern "extend import list with")

ghcide> ghcide
ghcide>   code actions
ghcide>     extend import actions
ghcide>       extend import list with multiple choices:
ghcide> No of code actions = 63
ghcide> OK (2.61s)
ghcide>
ghcide> All 1 tests passed (2.61s)
ghcide> Test suite ghcide-tests passed
stack test --test-arguments '--pattern "extend import list with"' --fast  2.65s user 0.57s system 106% cpu 3.022 total

```

Not the `No of code actions` output. They differ from different invocations.  The results are arbitrary as I run this command multiple times.

2020-11-18 20:34 UTC, pepeiborra commented
That's what the call to `waitForDiagnostics` is for. Did you remove it?

2020-11-18 23:33 UTC, gdevanla commented
> That's what the call to `waitForDiagnostics` is for. Did you remove it?

Nope. I have that whole piece of code intact.
```
  template contentA contentB range expectedAction expectedContentB = do                                                                                                                                           
      _docA <- createDoc "ModuleA.hs" "haskell" contentA                                                                                                                                           Add TODO2 Item   
      docB <- createDoc "ModuleB.hs" "haskell" contentB                                                                                                                                           Add TODO Item 1   
      _  <- waitForDiagnostics                                                                                                                                                                                      
      codeActions <- getCodeActions docB range                                                                                                                                                                      
      liftIO $ putStrLn $ "\nNo of code actions = " ++ (show $ length codeActions)                                                                                                                                  
      let CACodeAction action@CodeAction { _title = actionTitle } : _                                                                                                                                               
                  = sortOn (\(CACodeAction CodeAction{_title=x}) -> x) codeActions                                                                                                                                  
      liftIO $ expectedAction @=? actionTitle                                                                                                                                                                       
      executeCodeAction action                                                                                                                                                                                      
      contentAfterAction <- documentContents docB                                                                                                                                                                   
      liftIO $ expectedContentB @=? contentAfterAction          
```

2020-11-20 12:29 UTC, gdevanla commented
I ran the same command and printed out the diagnostics. Does this any clue?

```
$ time stack test --test-arguments '--pattern "extend import list"' --fast
ghcide-0.5.0: unregistering (local file changes: test/exe/Main.hs)
ghcide> configure (lib + exe + test)
ghcide> Configuring ghcide-0.5.0...
ghcide> build (lib + exe + test)
ghcide> Preprocessing executable 'ghcide-test-preprocessor' for ghcide-0.5.0..
ghcide> Building executable 'ghcide-test-preprocessor' for ghcide-0.5.0..
ghcide> Preprocessing library for ghcide-0.5.0..
ghcide> Building library for ghcide-0.5.0..
ghcide> Preprocessing executable 'ghcide' for ghcide-0.5.0..
ghcide> Building executable 'ghcide' for ghcide-0.5.0..
ghcide> Preprocessing test suite 'ghcide-tests' for ghcide-0.5.0..
ghcide> Building test suite 'ghcide-tests' for ghcide-0.5.0..
ghcide> [5 of 5] Compiling Main
ghcide> Linking .stack-work/dist/x86_64-linux/Cabal-3.2.0.0/build/ghcide-tests/ghcide-tests ...
ghcide> Preprocessing executable 'ghcide-bench' for ghcide-0.5.0..
ghcide> Building executable 'ghcide-bench' for ghcide-0.5.0..
ghcide> copy/register
ghcide> Installing executable ghcide-test-preprocessor in /home/devanla/fsf/hls/ghcide/.stack-work/install/x86_64-linux/d66a19e237aa809ac8cfd370cf12b025cd5720ba57179f663d7f8695a79ea3e5/8.10.1/bin
ghcide> Installing library in /home/devanla/fsf/hls/ghcide/.stack-work/install/x86_64-linux/d66a19e237aa809ac8cfd370cf12b025cd5720ba57179f663d7f8695a79ea3e5/8.10.1/lib/x86_64-linux-ghc-8.10.1/ghcide-0.5.0-BYH7o7yAusrAO60wzTJbHC
ghcide> Installing executable ghcide in /home/devanla/fsf/hls/ghcide/.stack-work/install/x86_64-linux/d66a19e237aa809ac8cfd370cf12b025cd5720ba57179f663d7f8695a79ea3e5/8.10.1/bin
ghcide> Installing executable ghcide-bench in /home/devanla/fsf/hls/ghcide/.stack-work/install/x86_64-linux/d66a19e237aa809ac8cfd370cf12b025cd5720ba57179f663d7f8695a79ea3e5/8.10.1/bin
ghcide> Registering library for ghcide-0.5.0..
ghcide> test (suite: ghcide-tests, args: --pattern "extend import list")

ghcide> ghcide
ghcide>   code actions
ghcide>     extend import actions
ghcide>       extend import list with multiple choices:
ghcide> Diag = [Diagnostic {_range = Range {_start = Position {_line = 0, _character = 21}, _end = Position {_line = 0, _character = 23}}, _severity = Just DsError, _code = Nothing, _source = Just "typecheck", _message = "Parse error: module header, import declaration\nor top-level declaration expected.", _tags = Nothing, _relatedInformation = Nothing}]
ghcide>
ghcide> No of code actions = 0
ghcide> FAIL
ghcide>         Exception: test/exe/Main.hs:(1127,11)-(1128,82): Non-exhaustive patterns in CACodeAction action@CodeAction {_title = actionTitle} : _
ghcide>
ghcide> 1 out of 1 tests failed (2.69s)
ghcide> Test suite ghcide-tests failed
Completed 2 action(s).
Test suite failure for package ghcide-0.5.0
    ghcide-tests:  exited with: ExitFailure 1
Logs printed to console

stack test --test-arguments '--pattern "extend import list"' --fast  12.24s user 3.58s system 94% cpu 16.714 total
```

Same command, run immediately but successful this time:
```
$ time stack test --test-arguments '--pattern "extend import list"' --fast
ghcide> test (suite: ghcide-tests, args: --pattern "extend import list")

ghcide> ghcide
ghcide>   code actions
ghcide>     extend import actions
ghcide>       extend import list with multiple choices:
ghcide> Diag = [Diagnostic {_range = Range {_start = Position {_line = 3, _character = 6}, _end = Position {_line = 3, _character = 14}}, _severity = Just DsError, _code = Nothing, _source = Just "typecheck", _message = "\8226 Variable not in scope: fromList :: [a0] -> t\n\8226 Perhaps you want to add \8216fromList\8217 to one of these import lists:\n    \8216Data.Map\8217 (/tmp/extra-dir-81931986100845/ModuleB.hs:2:1-18)\n    \8216Data.HashMap.Strict\8217 (/tmp/extra-dir-81931986100845/ModuleB.hs:3:1-29)", _tags = Nothing, _relatedInformation = Nothing}]
ghcide>
ghcide> No of code actions = 63
ghcide> OK (2.00s)
ghcide>
ghcide> All 1 tests passed (2.01s)
ghcide> Test suite ghcide-tests passed
stack test --test-arguments '--pattern "extend import list"' --fast  1.98s user 0.58s system 107% cpu 2.384 total

```

2020-11-20 21:00 UTC, pepeiborra commented
Please take a look at the LSP transport messages to get a better understanding of the issue

2020-11-21 18:27 UTC, pepeiborra approved these changes

2020-11-21 21:17 UTC, merged